---

- name: Nginx | APT key
  tags:
    - apt
  apt_key:
    id:  "{{ nginx_key }}"
    url: "{{ nginx_url }}"

- name: Nginx | repository
  tags:
    - apt
  apt_repository:
    repo: "{{ item }} http://nginx.org/packages/mainline/{{ ansible_distribution | lower }}/ {{ ansible_lsb.codename }} nginx"
    filename: 'nginx'
  with_items:
  - deb
  - deb-src

- name: Nginx | package
  tags:
    - package
  package:
    name: nginx

- name: Nginx | config dirs
  tags:
  - dir
  file:
    path: /etc/nginx/{{ item }}
    state: directory
    mode: 0750
  with_items:
  - conf.d
  - ssl
  - sites-available
  - sites-enabled

- name: Nginx | config
  tags:
  - config
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/"
  with_items:
    - nginx.conf
    - conf.d
    - "{{ nginx_keystore }}"
  notify: restart nginx

- name: Nginx | logrotate config
  tags:
    - logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/nginx

- name: Nginx | default site
  copy:
    src: default.nginx
    dest: /etc/nginx/sites-available/0default
  notify: reload nginx

- name: Nginx | enable default site
  tags:
  - site
  file:
    src: /etc/nginx/sites-available/0default
    dest: /etc/nginx/sites-enabled/0default
    state: link
  notify: reload nginx

- name: Nginx | service
  tags:
  - service
  service:
    name: nginx
    state: started
    enabled: yes

