---
# Usage:
# vars: 
#   site_name: <name>
#   site_config: <nginx template> (optional, default 'nginx.j2')
# include_role:
#   name: nginx
#   tasks_from: site.yml

- name: nginx | site | config
  tags:
  - nginx
  - config
  - site
  template:
    src: "{{ site_config | d('nginx.j2') }}"
    dest: /etc/nginx/sites-available/{{ site_name }}
  notify: reload nginx

- name: nginx | site | enable
  tags:
  - nginx
  - site
  file:
    src: /etc/nginx/sites-available/{{ site_name }}
    dest: /etc/nginx/sites-enabled/{{ site_name }}
    state: link
  notify: reload nginx
