---
# Usage:
# vars: 
#   site: <name>
#   site_cfg: <nginx template> (optional)
# include_role:
#   name: nginx
#   tasks_from: site.yml

- name: nginx | site | config
  tags:
    - nginx
    - config
    - site
  template:
    src: "{{ site_cfg | d(site ~ '.nginx.j2') }}"
    dest: /etc/nginx/sites-available/{{ site }}
  notify: reload nginx

- name: nginx | site | enable
  tags:
    - nginx
    - site
  file:
    src: /etc/nginx/sites-available/{{ site }}
    dest: /etc/nginx/sites-enabled/{{ site }}
    state: link
  notify: reload nginx
